### ISSUE TITLE
travis: pypi deployment section

### ISSUE THREAD

**Issue by drjova** [inveniosoftware/flask-iiif#45]
Update pypi section on travis

**Comment by lnielsen** [comment]
```yaml
deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: "Oz5MXWgL+vP+6/JdG0S9RRsftPhGsl3COp+ijzagnK1vkYvhAMbd9SZG10TNBadiOVR0pQZ1ikqOsyQwRxd9m2QYM7pMCl6fRFlPox+O6rdIRhl+VEHGswBMH/GNoQYEvn+4Nt/BdTnTxwZLybBWv3YuYbhdvynmEOSaqyXn6GE="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    conditions: $REQUIREMENTS = release
```
